### ISSUE TITLE
BrowserExitLock not working on WASM

### ISSUE THREAD

**Issue by keon1092704** [uecasm/Mirality.Blazor.Routing#4]
I have configured the BrowserExitLock on our application. And for the Blazor server everthing works fine. 
But on WASM when I try to close the tab no warning is shown.

**Comment by uecasm** [comment]
That's strange, since it was originally developed for WebAssembly and Server was more of an afterthought.

Can you provide more details about your environment?  What versions of all the framework and related packages are you using?  Did you place all the component code usages in the right places?

**Comment by keon1092704** [comment]
Thanks for the response. Indeed I found the error. Some JS file where corrupt. After fixing that it works perfect! Thanks
